### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by ghost** [S-mohan/color-picker#1]
想请问一下如何设置初始值 

我按照src下面 
interface Props {
  // 绑定值
  value?: string
  // 格式化
  format?: ColorFormat
  // 支持透明度？
  alpha?: boolean
  // 回调
  change?: Function
}
这样设置value并不生效不知道为什么 
还请大佬告诉一下
谢谢~

**Comment by S-mohan** [comment]
@wildccy 
不好意思，
问题出在checkColor这个方法上，element.style.color 返回的rgb颜色逗号间有空格，导致判断失败，现已修复，请参阅demo

```javascript
// 修复前
style.color === color
// 修复后
(style.color || '').replace(/\s/g, '') === color
```
#### demo
```javascript
const instance2 = new MoColorPicker($demo2, {
  value: '#6bc30d',
  alpha: true,
  change(color, colors) {
    run($demo2Result, this, colors)
  }
})
```

**Comment by ghost** [comment]
> @wildccy
> 不好意思，
> 问题出在checkColor这个方法上，element.style.color返回的rgb颜色逗号间有空格，导致判断失败，现已修复，请参阅demo
> 
> ```js
> //修复前
> 风格。颜色 ===彩
>  //修复后 
> （风格。颜色 ||  ' '）。替换（ / \ s / g， ' '） === color
> ```
> 
> #### 演示
> ```js
> const  instance2  =  new  MoColorPicker（$ demo2，{
>   价值： '＃6bc30d '，
>   alpha ： true，
>    更改（颜色，颜色）{
>      run（$ demo2Result，this，colors）
>   }
> }）
> ```

xiexie~
